const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert');
process.chdir(require('node:path').join(__dirname,'..'));
const context=new Proxy({measureText:text=>({width:text.length*7}),createLinearGradient:()=>({addColorStop(){}})}, {get:(o,k)=>k in o?o[k]:(()=>{})});
const createCanvas=()=>({getContext:()=>context,toBuffer:()=>Buffer.alloc(0)});
const source=fs.readFileSync('game.js','utf8').replace('})();','globalThis.debug={state,scenes,blocked,iso,route,go,changeScene,closePanel,ui,elevation,clearLine,inverse,surfaces};})();');
function setup(w,h){const c=createCanvas(w,h),els={},events={};const el=id=>els[id]??=(id==='game'?Object.assign(c,{addEventListener:(k,f)=>events[k]=f,setPointerCapture(){}}):{hidden:true,textContent:'',onclick:null,classList:{add(){},remove(){}},focus(){}});const win={innerWidth:w,innerHeight:h,devicePixelRatio:1,document:{getElementById:el,addEventListener(){}},addEventListener(){},performance:{now:()=>0},requestAnimationFrame:f=>win.frame=f,setTimeout:f=>f(),console};win.window=win;vm.createContext(win);vm.runInContext(fs.readFileSync('site-data.js','utf8'),win);vm.runInContext(source,win);let now=0;const tick=n=>{for(let i=0;i<n;i++)win.frame(now+=16)};tick(1);return{win,c,events,tick,els};}
for(const[w,h]of[[1200,900],[390,844],[844,390]]){const{win,c,tick,events,els}=setup(w,h),d=win.debug;const shot=()=>{};shot('site');const tap=point=>{const p=d.iso(point.x,point.y,d.elevation(point.x,point.y));events.pointerdown({clientX:p.x,clientY:p.y-22,pointerId:1,isPrimary:true});events.pointerup({clientX:p.x,clientY:p.y-22,pointerId:1,isPrimary:true});};
let prev={...d.state.player};tap(d.scenes.outside.points[0]);for(let i=0;i<600&&d.state.scene==='outside';i++){tick(1);if(d.state.scene==='outside')assert(!d.blocked(d.state.player.x,d.state.player.y));}assert.equal(d.state.scene,'inside','entrance');tick(2);tap(d.scenes.inside.points[0]);for(let i=0;i<600&&d.ui.sheet.hidden;i++)tick(1);assert(!d.ui.sheet.hidden,'exhibit');d.closePanel(d.ui.sheet);tap(d.scenes.inside.points[1]);tick(600);assert.equal(d.state.scene,'outside');
// Replacing a target must cancel the previous route; the terrace is reachable too.
d.go({x:9.6,y:24.7});tick(10);d.go({x:19,y:16.2});tick(1200);assert(Math.hypot(d.state.player.x-19,d.state.player.y-16.2)<.1,'retarget to garden');
// Long downhill path must visit both landings and keep height continuous.
d.go({x:9.6,y:24.7});let visited=new Set(),arrived=false;for(let i=0;i<1500;i++){prev={...d.state.player};const z=d.elevation(prev.x,prev.y);tick(1);assert(!d.blocked(d.state.player.x,d.state.player.y));const z2=d.elevation(d.state.player.x,d.state.player.y);assert(Math.abs(z2-z)<2.51,'no terrace edge jumping');if(Math.abs(z2-48)<.01)visited.add('middle');if(z2<1)visited.add('lower');if(!d.state.path.length){arrived=true;break;}}assert(arrived&&visited.size===2,'two stair flights');assert(Math.hypot(d.state.player.x-9.6,d.state.player.y-24.7)<.1);shot('lower');
// Stair-surface screen picking must recover the same world location.
for(const point of [{x:10.035,y:13.915},{x:8.78,y:21.25},{x:19,y:16.2}]){const p=d.iso(point.x,point.y,d.elevation(point.x,point.y)),q=d.inverse(p.x,p.y);assert(Math.hypot(q.x-point.x,q.y-point.y)<.01,'elevated picking');}
els.planMap.onclick();tick(1);shot('plan');const p=d.iso(19,16.2),q=d.inverse(p.x,p.y);assert(Math.hypot(q.x-19,q.y-16.2)<.01);els.zoomIn.onclick();tick(1);d.go({x:7.4,y:12.2});tick(1500);assert(Math.hypot(d.state.player.x-7.4,d.state.player.y-12.2)<.1,'uphill');console.log(w+'x'+h+' PASS entry/exhibit/exit/2 stair flights/uphill/plan/picking');}
